# Generated by Django 3.1.6 on 2021-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cards_open', models.BooleanField()),
                ('voting_open', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
