# Generated by Django 3.1.6 on 2021-02-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
