# Generated by Django 3.1.6 on 2021-02-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_auto_20210217_0619'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='columns.column'),
        ),
    ]
